### ISSUE TITLE
Debates : comment from user role

### ISSUE THREAD

**Issue by martanducas** [Platoniq/decidim-uoc#11]
Hi ha un component "debats" que acollirà comentaris per a millorar els reptes identificats: https://decidim-uoc-staging.uoclabs.uoc.es/processes/plaestrategic/f/2/ 

Es demana poder respondre els comentaris des del rol de la usuària, és a dir, que les tècniques de suport puguin respondre un comentari i que no apareixi que la resposta ha estat en nom seu (ni en nom del grup al que pertanyen), sino que apareixi com un comentari del(a) "tècnic(a) de suport".

Es pot?

**Comment by microstudi** [comment]
@marta-platoniq aixo que facin un grup a Decidim anomenat tècnic de suport i que responguin en el seu nom

**Comment by martanducas** [comment]
Ooook! T'ho compro, farem un altre grup de suport tècnic :) Gràcies!!

**Comment by martanducas** [comment]
Reobro pq crec que he trobat un mini-bug:

quan faig un comentari com a grup (Suport Tècnic) a la caixeta de darrer comentari surt el meu nom, no el grup des del qual he fet el comentari.

![image](https://user-images.githubusercontent.com/72607737/108110670-e20df100-7093-11eb-8c17-ada1e07f740d.png)

![image](https://user-images.githubusercontent.com/72607737/108110754-023db000-7094-11eb-8278-ebf59807c9b0.png)

**Comment by martanducas** [comment]
També passa aquí, a la pàgina on hi ha el llistat de debats (és el mateix comentari que vaig fer des de Suport Tècnic):

![image](https://user-images.githubusercontent.com/72607737/108358203-bbb09880-71ee-11eb-9f46-13ff430f1410.png)

**Comment by microstudi** [comment]
good catch! aquest bug podria anar a decidim core

**Comment by martanducas** [comment]
He fet report aquí: https://github.com/decidim/decidim/issues/7431

**Comment by martanducas** [comment]
Ja no hi haurà aq component debats dins del procés participatiu de la UOC. Queda reportat el bug a decidim, però aquí ja no ens afecta 👋
