### ISSUE TITLE
Answered proposals are displayed as rejected after been imported

### ISSUE THREAD

**Issue by martanducas** [Platoniq/decidim-uoc#12]
I have four proposals, 1 unanswered and 3 answered (accepted, rejected, in evaluation): https://demo.platoniq.net/processes/proces-bugs/f/98/

I try to import them in another proposals component. The 3 answered proposals are displayed as rejected in the new component: 
https://demo.platoniq.net/processes/proces-bugs/f/94/ (it only displays the unanswered proposal but if you check to display rejected proposals, you will see them all)

**Comment by martanducas** [comment]
Sembla ser que la 0.24 arregla aquest bug... haurem d'actualitzar abans d fer la demo, doncs ;)

**Comment by martanducas** [comment]
Ja està arreglat el bug per a les versions anteriors a les 0.24. Pendent de pujar

**Comment by microstudi** [comment]
Waiting for https://github.com/decidim/decidim/pull/7610

**Comment by martanducas** [comment]
Fixed :)
