### ISSUE TITLE
Logo with white background instead of transparent

### ISSUE THREAD

**Issue by martanducas** [Platoniq/decidim-uoc#23]
Podríem canviar el logo pq tingui el fons blanc, en comptes de transparent? Sino en molts llocs no es veu bé el text intermig Universitat Oberta de Catalunya. 

Aquí un jpg amb proposta d logo amb les mides reglamentàries:

![uoc_logo](https://user-images.githubusercontent.com/72607737/108861100-27c83d80-75ef-11eb-8433-647344b3cd6a.jpg)

**Comment by verarojman** [comment]
@marta-platoniq podries posar alguna captura dels llocs on no es veu bé? Et refereixes al logo quan apareix a la barra de dalt ⬇️ o a algun altre lloc? 
![image](https://user-images.githubusercontent.com/8806781/111141681-1c2fbd00-8584-11eb-9d1c-40b2f06cbaf1.png)

**Comment by martanducas** [comment]
Hola, Vera! ho va reportar Juan i crec que parlava pel butlletí. Veig que ja es veu bé, tanco.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/72607737/111183089-d8eb4380-85af-11eb-96e1-b7944b6b7e47.png">
