### ISSUE TITLE
Server error instead of validation error when writing a description longer than allowed

### ISSUE THREAD

**Issue by martanducas** [Platoniq/decidim-uoc#29]
A "Nous Reptes" creo una nova proposta amb la descripció més llarga del que està permès. Tot i que diu "Queden -41 caràcters", no em dóna error de validació en clicar continuar, sino que em dóna error de servidor.

![image](https://user-images.githubusercontent.com/72607737/109205013-550b1c00-77a6-11eb-99c0-cee613fd2e4e.png)

I en donar error, el menú es torna una mica boig, ho he reportat [aquí](https://github.com/Platoniq/decidim-module-decidim_awesome/issues/61) 

![image](https://user-images.githubusercontent.com/72607737/109205303-b3d09580-77a6-11eb-914c-9584ad956827.png)

**Comment by microstudi** [comment]
Nota: aixo es un bug de Decidim
![image](https://user-images.githubusercontent.com/1401520/109636768-4462f900-7b4c-11eb-8a02-194a4ec7d4b2.png)

**Comment by microstudi** [comment]
El fix seria aquest (penjem quan facin merge a core). https://github.com/decidim/decidim/pull/7495

**Comment by microstudi** [comment]
@marta-platoniq can you check if this is fixed?

**Comment by martanducas** [comment]
Sí, ja funciona bé. Gràcies!
