### ISSUE TITLE
Block user info edit

### ISSUE THREAD

**Issue by verarojman** [Platoniq/decidim-uoc#3]

**Comment by verarojman** [comment]
Closed by #15

**Comment by paarals** [comment]
@verarojman em sembla que s'ha perdut en algun moment aquests canvis, ara puc modificar aquests camps. tmabé està relacionat amb l'issue https://github.com/Platoniq/decidim-uoc/issues/3

**Comment by verarojman** [comment]
> @verarojman em sembla que s'ha perdut en algun moment aquests canvis, ara puc modificar aquests camps. tmabé està relacionat amb l'issue #3

Es poden modificar sempre i quan tinguis un usuari "normal", si tens un usuari OAuth no podràs.
