### ISSUE TITLE
Colors status text (accepted or rejected) is not displayed correctly

### ISSUE THREAD

**Issue by JuanLinaresLanzman** [Platoniq/decidim-uoc#32]
The color scheme of the proposals status does not provide a good contrast. It doesn't facilitates an universal accessibility to web contents. Two examples of "no resposta" and "descartada":

![image](https://user-images.githubusercontent.com/22983668/110778831-250e4f00-8263-11eb-93af-cfb74511117f.png)
![image](https://user-images.githubusercontent.com/22983668/110778781-16279c80-8263-11eb-82ad-5dc527506fe2.png)

Solution could be based on Web Content Accessibility Guidelines standards:
https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=143#distinguishable

Some useful tool to check text and background used colors
https://snook.ca/technical/colour_contrast/colour.html#fg=33FF33,bg=333333

**Comment by verarojman** [comment]
Closed by #48
