### ISSUE TITLE
Imatges de hero dels Grups de treball en català i castellà

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-uoc#35]
Les imatges del hero no es poden customitzar segons l'idioma, com sí el títol. Voldrien que en català aparegues una foto i en castellà un altre. 
Link: https://decidim-uoc-staging.uoclabs.uoc.es/work_groups
Fotos: 
[A.Banners 475x200px (1).zip](https://github.com/Platoniq/decidim-uoc/files/6122686/A.Banners.475x200px.1.zip)

**Comment by verarojman** [comment]
M'han comunicat per email que encara estan decidint sobre això, esperem a tenir les instruccions definitives.

**Comment by verarojman** [comment]
Finally closed by #52
