### ISSUE TITLE
Add assembly duplicator hack

### ISSUE THREAD

**Issue by verarojman** [Platoniq/decidim-uoc#4]

**Comment by paarals** [comment]
S'hauria de fer com indico en el video:
https://user-images.githubusercontent.com/40388743/108352287-eb5ba280-71e6-11eb-9853-5e7af5436a37.mp4
- [x] Direcció
- [ ] Grups de treball

**Comment by verarojman** [comment]
Closed by #21

**Comment by paarals** [comment]
hola @microstudi, finalment es dirà Governança. ara he demanat les traduccions en castellà i anglès also
