### ISSUE TITLE
Enlarge proposals title length

### ISSUE THREAD

**Issue by martanducas** [Platoniq/decidim-uoc#45]
Yes, el tamany a vegades importa, com en aquest cas 😜

Per a facilitar la importació dels reptes finals (component propostes) es va decidir que "Millores de reptes" fos un component propostes en comptes de debat. El problema és que tenen uns títols moooolt llargs i no hi caben al títol de propostes. Es pot fer més gran aquest títol?

Repte a debats:
![image](https://user-images.githubusercontent.com/72607737/111437941-f3363600-8703-11eb-9974-c12fe917f14f.png)

Repte a propostes (amb el títol tallat):
![image](https://user-images.githubusercontent.com/72607737/111438038-12cd5e80-8704-11eb-8a0e-0fc9c143c30f.png)

**Comment by martanducas** [comment]
Aps! Només caldria fer l'enlargement a l'admin

**Comment by martanducas** [comment]
@marta-platoniq això es podrà fer? a nivell tecnic, vull dir; el títol d'una proposta pot ser de 300 caracters en comptes de 150 a nivell BD? (ara tenim reu amb la uoc, per confirmar q ho podrem fer)

**Comment by verarojman** [comment]
@marta-platoniq es pot fer! 👍🏾

**Comment by verarojman** [comment]
Closed by #47
