### ISSUE TITLE
Better proposal import options

### ISSUE THREAD

**Issue by martanducas** [Platoniq/decidim-uoc#46]
Quan importem propostes d'un component propostes a un altre, tenim les següents opcions:

![image](https://user-images.githubusercontent.com/72607737/111610430-a3c33900-87db-11eb-893e-279a62a41ef8.png)

Necessitem poder tenir la opció d'importar també:
- Estat de la proposta (Acceptada/En Avaluació/No contestada...) + comentari de Resposta a la proposta ("Aquesta proposta ha estat acceptada perquè blablabla")
- Escollir importar només les propostes d'una determinada categoria o àmbit (ambdues opcions ens serveixen, quina seria més lògico-universal?)

PD: Tinc pendent fer un issue a metadecidim amb això

**Comment by martanducas** [comment]
Reportat a metadecidim: https://meta.decidim.org/processes/roadmap/f/122/proposals/16307

**Comment by verarojman** [comment]
PR: https://github.com/decidim/decidim/pull/7669

**Comment by martanducas** [comment]
done :) gràcies!

![image](https://user-images.githubusercontent.com/72607737/117784938-5e077780-b244-11eb-85e4-6abeeab63a3b.png)
