### ISSUE TITLE
Ordre Grups de Treball

### ISSUE THREAD

**Issue by martanducas** [Platoniq/decidim-uoc#58]
La visualització dels grups de treball (https://decidim-uoc-staging.uoclabs.uoc.es/work_groups) hauria de ser seguint aquest ordre:
1. Impuls a la transversalitat... (id 11)
2. Governança col·laborativa (id 22)
3. Aposta ferma per la... (id 33)
4. Potenciació de la competitivitat... (id 44)
5. Foment de l'excel·lència en la recerca (id 55)

Ooooh! Just un order by id ens serveix :)

**Comment by martanducas** [comment]
Nota de la UOC: Si es complica el tema de l'ordre dels grups, massa hores o massa gestió per fer-ho, avisa'ns i valorarem què fer, sí?

**Comment by verarojman** [comment]
Closed by #73
