### ISSUE TITLE
Create custom OAuth workflow

### ISSUE THREAD

**Issue by verarojman** [Platoniq/decidim-uoc#6]

**Comment by paarals** [comment]
Una pregunta tècnica: seria possible un pas previ a l'accés a la plataforma (una vegada fet l'Oauth) per tal que les persones acceptin les condicions d'ús que demana la nostra assessoria jurídica?

**Comment by verarojman** [comment]
> Una pregunta tècnica: seria possible un pas previ a l'accés a la plataforma (una vegada fet l'Oauth) per tal que les persones acceptin les condicions d'ús que demana la nostra assessoria jurídica?

Això ja és el comportament per defecte crec, un cop et registres amb OAuth et fa acceptar els termes i condicions d'ús

**Comment by verarojman** [comment]
Closed by #56  .. #68
