### ISSUE TITLE
Proposals : filter changes component ID

### ISSUE THREAD

**Issue by martanducas** [Platoniq/decidim-uoc#85]
Quan filtro, l'enllaç del filtre em canvia el ID del component.

Anar a [https://decidim.uoc.edu/processes/plaestrategic/f/5/](https://decidim.uoc.edu/processes/plaestrategic/f/5/) > estem al component amb ID 5.

Clicar sobre qualsevol opció de filtre > a la URL, canvia l'ID de component a 6.

**Comment by martanducas** [comment]
Reportat a Decidim: [https://github.com/decidim/decidim/issues/8003](https://github.com/decidim/decidim/issues/8003)

**Comment by paarals** [comment]
era un tema de la cache
